### ISSUE TITLE
Error: Cannot find module 'babel-register'

### ISSUE THREAD

**Issue by RootViper4** [cassidoo/todometer#72]
i got this while running

App threw an error during load
Error: Cannot find module 'babel-register'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\TheCode\Documents\todometer-master\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\TheCode\Documents\todometer-master\bootstrapper.js:2:1)
    at Object.<anonymous> (C:\Users\TheCode\Documents\todometer-master\bootstrapper.js:5:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by RootViper4** [comment]
sorry i got it
